<?php
/**
 * GetAnalytics200ResponseValue
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  blockmate
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Blockmate
 *
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace blockmate\Model;

use \ArrayAccess;
use \blockmate\ObjectSerializer;

/**
 * GetAnalytics200ResponseValue Class Doc Comment
 *
 * @category Class
 * @package  blockmate
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetAnalytics200ResponseValue implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetAnalytics_200_response_value';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sum_txs_all_forever_onchain' => 'float',
        'sum_txs_all_forever_nft' => 'float',
        'sum_txs_all_forever_gaming' => 'float',
        'sum_txs_all_forever_gambling' => 'float',
        'sum_txs_all_365_onchain' => 'float',
        'sum_txs_all_365_nft' => 'float',
        'sum_txs_all_365_gaming' => 'float',
        'sum_txs_all_365_gambling' => 'float',
        'sum_txs_all_31_60_onchain' => 'float',
        'sum_txs_all_31_60_nft' => 'float',
        'sum_txs_all_31_60_gaming' => 'float',
        'sum_txs_all_31_60_gambling' => 'float',
        'sum_txs_all_30_onchain' => 'float',
        'sum_txs_all_30_nft' => 'float',
        'sum_txs_all_30_gaming' => 'float',
        'sum_txs_all_30_gambling' => 'float',
        'sum_txs_all_7_onchain' => 'float',
        'sum_txs_all_7_nft' => 'float',
        'sum_txs_all_7_gaming' => 'float',
        'sum_txs_all_7_gambling' => 'float',
        'sum_txs_in_forever_onchain' => 'float',
        'sum_txs_in_forever_nft' => 'float',
        'sum_txs_in_forever_gaming' => 'float',
        'sum_txs_in_forever_gambling' => 'float',
        'sum_txs_in_365_onchain' => 'float',
        'sum_txs_in_365_nft' => 'float',
        'sum_txs_in_365_gaming' => 'float',
        'sum_txs_in_365_gambling' => 'float',
        'sum_txs_in_31_60_onchain' => 'float',
        'sum_txs_in_31_60_nft' => 'float',
        'sum_txs_in_31_60_gaming' => 'float',
        'sum_txs_in_31_60_gambling' => 'float',
        'sum_txs_in_30_onchain' => 'float',
        'sum_txs_in_30_nft' => 'float',
        'sum_txs_in_30_gaming' => 'float',
        'sum_txs_in_30_gambling' => 'float',
        'sum_txs_in_7_onchain' => 'float',
        'sum_txs_in_7_nft' => 'float',
        'sum_txs_in_7_gaming' => 'float',
        'sum_txs_in_7_gambling' => 'float',
        'sum_txs_out_forever_onchain' => 'float',
        'sum_txs_out_forever_nft' => 'float',
        'sum_txs_out_forever_gaming' => 'float',
        'sum_txs_out_forever_gambling' => 'float',
        'sum_txs_out_365_onchain' => 'float',
        'sum_txs_out_365_nft' => 'float',
        'sum_txs_out_365_gaming' => 'float',
        'sum_txs_out_365_gambling' => 'float',
        'sum_txs_out_31_60_onchain' => 'float',
        'sum_txs_out_31_60_nft' => 'float',
        'sum_txs_out_31_60_gaming' => 'float',
        'sum_txs_out_31_60_gambling' => 'float',
        'sum_txs_out_30_onchain' => 'float',
        'sum_txs_out_30_nft' => 'float',
        'sum_txs_out_30_gaming' => 'float',
        'sum_txs_out_30_gambling' => 'float',
        'sum_txs_out_7_onchain' => 'float',
        'sum_txs_out_7_nft' => 'float',
        'sum_txs_out_7_gaming' => 'float',
        'sum_txs_out_7_gambling' => 'float',
        'max_balance_forever_onchain' => 'float',
        'max_balance_forever_nft' => 'float',
        'max_balance_forever_gaming' => 'float',
        'max_balance_forever_gambling' => 'float',
        'max_balance_365_onchain' => 'float',
        'max_balance_365_nft' => 'float',
        'max_balance_365_gaming' => 'float',
        'max_balance_365_gambling' => 'float',
        'max_balance_31_60_onchain' => 'float',
        'max_balance_31_60_nft' => 'float',
        'max_balance_31_60_gaming' => 'float',
        'max_balance_31_60_gambling' => 'float',
        'max_balance_30_onchain' => 'float',
        'max_balance_30_nft' => 'float',
        'max_balance_30_gaming' => 'float',
        'max_balance_30_gambling' => 'float',
        'max_balance_7_onchain' => 'float',
        'max_balance_7_nft' => 'float',
        'max_balance_7_gaming' => 'float',
        'max_balance_7_gambling' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sum_txs_all_forever_onchain' => null,
        'sum_txs_all_forever_nft' => null,
        'sum_txs_all_forever_gaming' => null,
        'sum_txs_all_forever_gambling' => null,
        'sum_txs_all_365_onchain' => null,
        'sum_txs_all_365_nft' => null,
        'sum_txs_all_365_gaming' => null,
        'sum_txs_all_365_gambling' => null,
        'sum_txs_all_31_60_onchain' => null,
        'sum_txs_all_31_60_nft' => null,
        'sum_txs_all_31_60_gaming' => null,
        'sum_txs_all_31_60_gambling' => null,
        'sum_txs_all_30_onchain' => null,
        'sum_txs_all_30_nft' => null,
        'sum_txs_all_30_gaming' => null,
        'sum_txs_all_30_gambling' => null,
        'sum_txs_all_7_onchain' => null,
        'sum_txs_all_7_nft' => null,
        'sum_txs_all_7_gaming' => null,
        'sum_txs_all_7_gambling' => null,
        'sum_txs_in_forever_onchain' => null,
        'sum_txs_in_forever_nft' => null,
        'sum_txs_in_forever_gaming' => null,
        'sum_txs_in_forever_gambling' => null,
        'sum_txs_in_365_onchain' => null,
        'sum_txs_in_365_nft' => null,
        'sum_txs_in_365_gaming' => null,
        'sum_txs_in_365_gambling' => null,
        'sum_txs_in_31_60_onchain' => null,
        'sum_txs_in_31_60_nft' => null,
        'sum_txs_in_31_60_gaming' => null,
        'sum_txs_in_31_60_gambling' => null,
        'sum_txs_in_30_onchain' => null,
        'sum_txs_in_30_nft' => null,
        'sum_txs_in_30_gaming' => null,
        'sum_txs_in_30_gambling' => null,
        'sum_txs_in_7_onchain' => null,
        'sum_txs_in_7_nft' => null,
        'sum_txs_in_7_gaming' => null,
        'sum_txs_in_7_gambling' => null,
        'sum_txs_out_forever_onchain' => null,
        'sum_txs_out_forever_nft' => null,
        'sum_txs_out_forever_gaming' => null,
        'sum_txs_out_forever_gambling' => null,
        'sum_txs_out_365_onchain' => null,
        'sum_txs_out_365_nft' => null,
        'sum_txs_out_365_gaming' => null,
        'sum_txs_out_365_gambling' => null,
        'sum_txs_out_31_60_onchain' => null,
        'sum_txs_out_31_60_nft' => null,
        'sum_txs_out_31_60_gaming' => null,
        'sum_txs_out_31_60_gambling' => null,
        'sum_txs_out_30_onchain' => null,
        'sum_txs_out_30_nft' => null,
        'sum_txs_out_30_gaming' => null,
        'sum_txs_out_30_gambling' => null,
        'sum_txs_out_7_onchain' => null,
        'sum_txs_out_7_nft' => null,
        'sum_txs_out_7_gaming' => null,
        'sum_txs_out_7_gambling' => null,
        'max_balance_forever_onchain' => null,
        'max_balance_forever_nft' => null,
        'max_balance_forever_gaming' => null,
        'max_balance_forever_gambling' => null,
        'max_balance_365_onchain' => null,
        'max_balance_365_nft' => null,
        'max_balance_365_gaming' => null,
        'max_balance_365_gambling' => null,
        'max_balance_31_60_onchain' => null,
        'max_balance_31_60_nft' => null,
        'max_balance_31_60_gaming' => null,
        'max_balance_31_60_gambling' => null,
        'max_balance_30_onchain' => null,
        'max_balance_30_nft' => null,
        'max_balance_30_gaming' => null,
        'max_balance_30_gambling' => null,
        'max_balance_7_onchain' => null,
        'max_balance_7_nft' => null,
        'max_balance_7_gaming' => null,
        'max_balance_7_gambling' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sum_txs_all_forever_onchain' => false,
		'sum_txs_all_forever_nft' => false,
		'sum_txs_all_forever_gaming' => false,
		'sum_txs_all_forever_gambling' => false,
		'sum_txs_all_365_onchain' => false,
		'sum_txs_all_365_nft' => false,
		'sum_txs_all_365_gaming' => false,
		'sum_txs_all_365_gambling' => false,
		'sum_txs_all_31_60_onchain' => false,
		'sum_txs_all_31_60_nft' => false,
		'sum_txs_all_31_60_gaming' => false,
		'sum_txs_all_31_60_gambling' => false,
		'sum_txs_all_30_onchain' => false,
		'sum_txs_all_30_nft' => false,
		'sum_txs_all_30_gaming' => false,
		'sum_txs_all_30_gambling' => false,
		'sum_txs_all_7_onchain' => false,
		'sum_txs_all_7_nft' => false,
		'sum_txs_all_7_gaming' => false,
		'sum_txs_all_7_gambling' => false,
		'sum_txs_in_forever_onchain' => false,
		'sum_txs_in_forever_nft' => false,
		'sum_txs_in_forever_gaming' => false,
		'sum_txs_in_forever_gambling' => false,
		'sum_txs_in_365_onchain' => false,
		'sum_txs_in_365_nft' => false,
		'sum_txs_in_365_gaming' => false,
		'sum_txs_in_365_gambling' => false,
		'sum_txs_in_31_60_onchain' => false,
		'sum_txs_in_31_60_nft' => false,
		'sum_txs_in_31_60_gaming' => false,
		'sum_txs_in_31_60_gambling' => false,
		'sum_txs_in_30_onchain' => false,
		'sum_txs_in_30_nft' => false,
		'sum_txs_in_30_gaming' => false,
		'sum_txs_in_30_gambling' => false,
		'sum_txs_in_7_onchain' => false,
		'sum_txs_in_7_nft' => false,
		'sum_txs_in_7_gaming' => false,
		'sum_txs_in_7_gambling' => false,
		'sum_txs_out_forever_onchain' => false,
		'sum_txs_out_forever_nft' => false,
		'sum_txs_out_forever_gaming' => false,
		'sum_txs_out_forever_gambling' => false,
		'sum_txs_out_365_onchain' => false,
		'sum_txs_out_365_nft' => false,
		'sum_txs_out_365_gaming' => false,
		'sum_txs_out_365_gambling' => false,
		'sum_txs_out_31_60_onchain' => false,
		'sum_txs_out_31_60_nft' => false,
		'sum_txs_out_31_60_gaming' => false,
		'sum_txs_out_31_60_gambling' => false,
		'sum_txs_out_30_onchain' => false,
		'sum_txs_out_30_nft' => false,
		'sum_txs_out_30_gaming' => false,
		'sum_txs_out_30_gambling' => false,
		'sum_txs_out_7_onchain' => false,
		'sum_txs_out_7_nft' => false,
		'sum_txs_out_7_gaming' => false,
		'sum_txs_out_7_gambling' => false,
		'max_balance_forever_onchain' => false,
		'max_balance_forever_nft' => false,
		'max_balance_forever_gaming' => false,
		'max_balance_forever_gambling' => false,
		'max_balance_365_onchain' => false,
		'max_balance_365_nft' => false,
		'max_balance_365_gaming' => false,
		'max_balance_365_gambling' => false,
		'max_balance_31_60_onchain' => false,
		'max_balance_31_60_nft' => false,
		'max_balance_31_60_gaming' => false,
		'max_balance_31_60_gambling' => false,
		'max_balance_30_onchain' => false,
		'max_balance_30_nft' => false,
		'max_balance_30_gaming' => false,
		'max_balance_30_gambling' => false,
		'max_balance_7_onchain' => false,
		'max_balance_7_nft' => false,
		'max_balance_7_gaming' => false,
		'max_balance_7_gambling' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sum_txs_all_forever_onchain' => 'sum_txs_all_forever_onchain',
        'sum_txs_all_forever_nft' => 'sum_txs_all_forever_nft',
        'sum_txs_all_forever_gaming' => 'sum_txs_all_forever_gaming',
        'sum_txs_all_forever_gambling' => 'sum_txs_all_forever_gambling',
        'sum_txs_all_365_onchain' => 'sum_txs_all_365_onchain',
        'sum_txs_all_365_nft' => 'sum_txs_all_365_nft',
        'sum_txs_all_365_gaming' => 'sum_txs_all_365_gaming',
        'sum_txs_all_365_gambling' => 'sum_txs_all_365_gambling',
        'sum_txs_all_31_60_onchain' => 'sum_txs_all_31_60_onchain',
        'sum_txs_all_31_60_nft' => 'sum_txs_all_31_60_nft',
        'sum_txs_all_31_60_gaming' => 'sum_txs_all_31_60_gaming',
        'sum_txs_all_31_60_gambling' => 'sum_txs_all_31_60_gambling',
        'sum_txs_all_30_onchain' => 'sum_txs_all_30_onchain',
        'sum_txs_all_30_nft' => 'sum_txs_all_30_nft',
        'sum_txs_all_30_gaming' => 'sum_txs_all_30_gaming',
        'sum_txs_all_30_gambling' => 'sum_txs_all_30_gambling',
        'sum_txs_all_7_onchain' => 'sum_txs_all_7_onchain',
        'sum_txs_all_7_nft' => 'sum_txs_all_7_nft',
        'sum_txs_all_7_gaming' => 'sum_txs_all_7_gaming',
        'sum_txs_all_7_gambling' => 'sum_txs_all_7_gambling',
        'sum_txs_in_forever_onchain' => 'sum_txs_in_forever_onchain',
        'sum_txs_in_forever_nft' => 'sum_txs_in_forever_nft',
        'sum_txs_in_forever_gaming' => 'sum_txs_in_forever_gaming',
        'sum_txs_in_forever_gambling' => 'sum_txs_in_forever_gambling',
        'sum_txs_in_365_onchain' => 'sum_txs_in_365_onchain',
        'sum_txs_in_365_nft' => 'sum_txs_in_365_nft',
        'sum_txs_in_365_gaming' => 'sum_txs_in_365_gaming',
        'sum_txs_in_365_gambling' => 'sum_txs_in_365_gambling',
        'sum_txs_in_31_60_onchain' => 'sum_txs_in_31_60_onchain',
        'sum_txs_in_31_60_nft' => 'sum_txs_in_31_60_nft',
        'sum_txs_in_31_60_gaming' => 'sum_txs_in_31_60_gaming',
        'sum_txs_in_31_60_gambling' => 'sum_txs_in_31_60_gambling',
        'sum_txs_in_30_onchain' => 'sum_txs_in_30_onchain',
        'sum_txs_in_30_nft' => 'sum_txs_in_30_nft',
        'sum_txs_in_30_gaming' => 'sum_txs_in_30_gaming',
        'sum_txs_in_30_gambling' => 'sum_txs_in_30_gambling',
        'sum_txs_in_7_onchain' => 'sum_txs_in_7_onchain',
        'sum_txs_in_7_nft' => 'sum_txs_in_7_nft',
        'sum_txs_in_7_gaming' => 'sum_txs_in_7_gaming',
        'sum_txs_in_7_gambling' => 'sum_txs_in_7_gambling',
        'sum_txs_out_forever_onchain' => 'sum_txs_out_forever_onchain',
        'sum_txs_out_forever_nft' => 'sum_txs_out_forever_nft',
        'sum_txs_out_forever_gaming' => 'sum_txs_out_forever_gaming',
        'sum_txs_out_forever_gambling' => 'sum_txs_out_forever_gambling',
        'sum_txs_out_365_onchain' => 'sum_txs_out_365_onchain',
        'sum_txs_out_365_nft' => 'sum_txs_out_365_nft',
        'sum_txs_out_365_gaming' => 'sum_txs_out_365_gaming',
        'sum_txs_out_365_gambling' => 'sum_txs_out_365_gambling',
        'sum_txs_out_31_60_onchain' => 'sum_txs_out_31_60_onchain',
        'sum_txs_out_31_60_nft' => 'sum_txs_out_31_60_nft',
        'sum_txs_out_31_60_gaming' => 'sum_txs_out_31_60_gaming',
        'sum_txs_out_31_60_gambling' => 'sum_txs_out_31_60_gambling',
        'sum_txs_out_30_onchain' => 'sum_txs_out_30_onchain',
        'sum_txs_out_30_nft' => 'sum_txs_out_30_nft',
        'sum_txs_out_30_gaming' => 'sum_txs_out_30_gaming',
        'sum_txs_out_30_gambling' => 'sum_txs_out_30_gambling',
        'sum_txs_out_7_onchain' => 'sum_txs_out_7_onchain',
        'sum_txs_out_7_nft' => 'sum_txs_out_7_nft',
        'sum_txs_out_7_gaming' => 'sum_txs_out_7_gaming',
        'sum_txs_out_7_gambling' => 'sum_txs_out_7_gambling',
        'max_balance_forever_onchain' => 'max_balance_forever_onchain',
        'max_balance_forever_nft' => 'max_balance_forever_nft',
        'max_balance_forever_gaming' => 'max_balance_forever_gaming',
        'max_balance_forever_gambling' => 'max_balance_forever_gambling',
        'max_balance_365_onchain' => 'max_balance_365_onchain',
        'max_balance_365_nft' => 'max_balance_365_nft',
        'max_balance_365_gaming' => 'max_balance_365_gaming',
        'max_balance_365_gambling' => 'max_balance_365_gambling',
        'max_balance_31_60_onchain' => 'max_balance_31_60_onchain',
        'max_balance_31_60_nft' => 'max_balance_31_60_nft',
        'max_balance_31_60_gaming' => 'max_balance_31_60_gaming',
        'max_balance_31_60_gambling' => 'max_balance_31_60_gambling',
        'max_balance_30_onchain' => 'max_balance_30_onchain',
        'max_balance_30_nft' => 'max_balance_30_nft',
        'max_balance_30_gaming' => 'max_balance_30_gaming',
        'max_balance_30_gambling' => 'max_balance_30_gambling',
        'max_balance_7_onchain' => 'max_balance_7_onchain',
        'max_balance_7_nft' => 'max_balance_7_nft',
        'max_balance_7_gaming' => 'max_balance_7_gaming',
        'max_balance_7_gambling' => 'max_balance_7_gambling'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sum_txs_all_forever_onchain' => 'setSumTxsAllForeverOnchain',
        'sum_txs_all_forever_nft' => 'setSumTxsAllForeverNft',
        'sum_txs_all_forever_gaming' => 'setSumTxsAllForeverGaming',
        'sum_txs_all_forever_gambling' => 'setSumTxsAllForeverGambling',
        'sum_txs_all_365_onchain' => 'setSumTxsAll365Onchain',
        'sum_txs_all_365_nft' => 'setSumTxsAll365Nft',
        'sum_txs_all_365_gaming' => 'setSumTxsAll365Gaming',
        'sum_txs_all_365_gambling' => 'setSumTxsAll365Gambling',
        'sum_txs_all_31_60_onchain' => 'setSumTxsAll3160Onchain',
        'sum_txs_all_31_60_nft' => 'setSumTxsAll3160Nft',
        'sum_txs_all_31_60_gaming' => 'setSumTxsAll3160Gaming',
        'sum_txs_all_31_60_gambling' => 'setSumTxsAll3160Gambling',
        'sum_txs_all_30_onchain' => 'setSumTxsAll30Onchain',
        'sum_txs_all_30_nft' => 'setSumTxsAll30Nft',
        'sum_txs_all_30_gaming' => 'setSumTxsAll30Gaming',
        'sum_txs_all_30_gambling' => 'setSumTxsAll30Gambling',
        'sum_txs_all_7_onchain' => 'setSumTxsAll7Onchain',
        'sum_txs_all_7_nft' => 'setSumTxsAll7Nft',
        'sum_txs_all_7_gaming' => 'setSumTxsAll7Gaming',
        'sum_txs_all_7_gambling' => 'setSumTxsAll7Gambling',
        'sum_txs_in_forever_onchain' => 'setSumTxsInForeverOnchain',
        'sum_txs_in_forever_nft' => 'setSumTxsInForeverNft',
        'sum_txs_in_forever_gaming' => 'setSumTxsInForeverGaming',
        'sum_txs_in_forever_gambling' => 'setSumTxsInForeverGambling',
        'sum_txs_in_365_onchain' => 'setSumTxsIn365Onchain',
        'sum_txs_in_365_nft' => 'setSumTxsIn365Nft',
        'sum_txs_in_365_gaming' => 'setSumTxsIn365Gaming',
        'sum_txs_in_365_gambling' => 'setSumTxsIn365Gambling',
        'sum_txs_in_31_60_onchain' => 'setSumTxsIn3160Onchain',
        'sum_txs_in_31_60_nft' => 'setSumTxsIn3160Nft',
        'sum_txs_in_31_60_gaming' => 'setSumTxsIn3160Gaming',
        'sum_txs_in_31_60_gambling' => 'setSumTxsIn3160Gambling',
        'sum_txs_in_30_onchain' => 'setSumTxsIn30Onchain',
        'sum_txs_in_30_nft' => 'setSumTxsIn30Nft',
        'sum_txs_in_30_gaming' => 'setSumTxsIn30Gaming',
        'sum_txs_in_30_gambling' => 'setSumTxsIn30Gambling',
        'sum_txs_in_7_onchain' => 'setSumTxsIn7Onchain',
        'sum_txs_in_7_nft' => 'setSumTxsIn7Nft',
        'sum_txs_in_7_gaming' => 'setSumTxsIn7Gaming',
        'sum_txs_in_7_gambling' => 'setSumTxsIn7Gambling',
        'sum_txs_out_forever_onchain' => 'setSumTxsOutForeverOnchain',
        'sum_txs_out_forever_nft' => 'setSumTxsOutForeverNft',
        'sum_txs_out_forever_gaming' => 'setSumTxsOutForeverGaming',
        'sum_txs_out_forever_gambling' => 'setSumTxsOutForeverGambling',
        'sum_txs_out_365_onchain' => 'setSumTxsOut365Onchain',
        'sum_txs_out_365_nft' => 'setSumTxsOut365Nft',
        'sum_txs_out_365_gaming' => 'setSumTxsOut365Gaming',
        'sum_txs_out_365_gambling' => 'setSumTxsOut365Gambling',
        'sum_txs_out_31_60_onchain' => 'setSumTxsOut3160Onchain',
        'sum_txs_out_31_60_nft' => 'setSumTxsOut3160Nft',
        'sum_txs_out_31_60_gaming' => 'setSumTxsOut3160Gaming',
        'sum_txs_out_31_60_gambling' => 'setSumTxsOut3160Gambling',
        'sum_txs_out_30_onchain' => 'setSumTxsOut30Onchain',
        'sum_txs_out_30_nft' => 'setSumTxsOut30Nft',
        'sum_txs_out_30_gaming' => 'setSumTxsOut30Gaming',
        'sum_txs_out_30_gambling' => 'setSumTxsOut30Gambling',
        'sum_txs_out_7_onchain' => 'setSumTxsOut7Onchain',
        'sum_txs_out_7_nft' => 'setSumTxsOut7Nft',
        'sum_txs_out_7_gaming' => 'setSumTxsOut7Gaming',
        'sum_txs_out_7_gambling' => 'setSumTxsOut7Gambling',
        'max_balance_forever_onchain' => 'setMaxBalanceForeverOnchain',
        'max_balance_forever_nft' => 'setMaxBalanceForeverNft',
        'max_balance_forever_gaming' => 'setMaxBalanceForeverGaming',
        'max_balance_forever_gambling' => 'setMaxBalanceForeverGambling',
        'max_balance_365_onchain' => 'setMaxBalance365Onchain',
        'max_balance_365_nft' => 'setMaxBalance365Nft',
        'max_balance_365_gaming' => 'setMaxBalance365Gaming',
        'max_balance_365_gambling' => 'setMaxBalance365Gambling',
        'max_balance_31_60_onchain' => 'setMaxBalance3160Onchain',
        'max_balance_31_60_nft' => 'setMaxBalance3160Nft',
        'max_balance_31_60_gaming' => 'setMaxBalance3160Gaming',
        'max_balance_31_60_gambling' => 'setMaxBalance3160Gambling',
        'max_balance_30_onchain' => 'setMaxBalance30Onchain',
        'max_balance_30_nft' => 'setMaxBalance30Nft',
        'max_balance_30_gaming' => 'setMaxBalance30Gaming',
        'max_balance_30_gambling' => 'setMaxBalance30Gambling',
        'max_balance_7_onchain' => 'setMaxBalance7Onchain',
        'max_balance_7_nft' => 'setMaxBalance7Nft',
        'max_balance_7_gaming' => 'setMaxBalance7Gaming',
        'max_balance_7_gambling' => 'setMaxBalance7Gambling'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sum_txs_all_forever_onchain' => 'getSumTxsAllForeverOnchain',
        'sum_txs_all_forever_nft' => 'getSumTxsAllForeverNft',
        'sum_txs_all_forever_gaming' => 'getSumTxsAllForeverGaming',
        'sum_txs_all_forever_gambling' => 'getSumTxsAllForeverGambling',
        'sum_txs_all_365_onchain' => 'getSumTxsAll365Onchain',
        'sum_txs_all_365_nft' => 'getSumTxsAll365Nft',
        'sum_txs_all_365_gaming' => 'getSumTxsAll365Gaming',
        'sum_txs_all_365_gambling' => 'getSumTxsAll365Gambling',
        'sum_txs_all_31_60_onchain' => 'getSumTxsAll3160Onchain',
        'sum_txs_all_31_60_nft' => 'getSumTxsAll3160Nft',
        'sum_txs_all_31_60_gaming' => 'getSumTxsAll3160Gaming',
        'sum_txs_all_31_60_gambling' => 'getSumTxsAll3160Gambling',
        'sum_txs_all_30_onchain' => 'getSumTxsAll30Onchain',
        'sum_txs_all_30_nft' => 'getSumTxsAll30Nft',
        'sum_txs_all_30_gaming' => 'getSumTxsAll30Gaming',
        'sum_txs_all_30_gambling' => 'getSumTxsAll30Gambling',
        'sum_txs_all_7_onchain' => 'getSumTxsAll7Onchain',
        'sum_txs_all_7_nft' => 'getSumTxsAll7Nft',
        'sum_txs_all_7_gaming' => 'getSumTxsAll7Gaming',
        'sum_txs_all_7_gambling' => 'getSumTxsAll7Gambling',
        'sum_txs_in_forever_onchain' => 'getSumTxsInForeverOnchain',
        'sum_txs_in_forever_nft' => 'getSumTxsInForeverNft',
        'sum_txs_in_forever_gaming' => 'getSumTxsInForeverGaming',
        'sum_txs_in_forever_gambling' => 'getSumTxsInForeverGambling',
        'sum_txs_in_365_onchain' => 'getSumTxsIn365Onchain',
        'sum_txs_in_365_nft' => 'getSumTxsIn365Nft',
        'sum_txs_in_365_gaming' => 'getSumTxsIn365Gaming',
        'sum_txs_in_365_gambling' => 'getSumTxsIn365Gambling',
        'sum_txs_in_31_60_onchain' => 'getSumTxsIn3160Onchain',
        'sum_txs_in_31_60_nft' => 'getSumTxsIn3160Nft',
        'sum_txs_in_31_60_gaming' => 'getSumTxsIn3160Gaming',
        'sum_txs_in_31_60_gambling' => 'getSumTxsIn3160Gambling',
        'sum_txs_in_30_onchain' => 'getSumTxsIn30Onchain',
        'sum_txs_in_30_nft' => 'getSumTxsIn30Nft',
        'sum_txs_in_30_gaming' => 'getSumTxsIn30Gaming',
        'sum_txs_in_30_gambling' => 'getSumTxsIn30Gambling',
        'sum_txs_in_7_onchain' => 'getSumTxsIn7Onchain',
        'sum_txs_in_7_nft' => 'getSumTxsIn7Nft',
        'sum_txs_in_7_gaming' => 'getSumTxsIn7Gaming',
        'sum_txs_in_7_gambling' => 'getSumTxsIn7Gambling',
        'sum_txs_out_forever_onchain' => 'getSumTxsOutForeverOnchain',
        'sum_txs_out_forever_nft' => 'getSumTxsOutForeverNft',
        'sum_txs_out_forever_gaming' => 'getSumTxsOutForeverGaming',
        'sum_txs_out_forever_gambling' => 'getSumTxsOutForeverGambling',
        'sum_txs_out_365_onchain' => 'getSumTxsOut365Onchain',
        'sum_txs_out_365_nft' => 'getSumTxsOut365Nft',
        'sum_txs_out_365_gaming' => 'getSumTxsOut365Gaming',
        'sum_txs_out_365_gambling' => 'getSumTxsOut365Gambling',
        'sum_txs_out_31_60_onchain' => 'getSumTxsOut3160Onchain',
        'sum_txs_out_31_60_nft' => 'getSumTxsOut3160Nft',
        'sum_txs_out_31_60_gaming' => 'getSumTxsOut3160Gaming',
        'sum_txs_out_31_60_gambling' => 'getSumTxsOut3160Gambling',
        'sum_txs_out_30_onchain' => 'getSumTxsOut30Onchain',
        'sum_txs_out_30_nft' => 'getSumTxsOut30Nft',
        'sum_txs_out_30_gaming' => 'getSumTxsOut30Gaming',
        'sum_txs_out_30_gambling' => 'getSumTxsOut30Gambling',
        'sum_txs_out_7_onchain' => 'getSumTxsOut7Onchain',
        'sum_txs_out_7_nft' => 'getSumTxsOut7Nft',
        'sum_txs_out_7_gaming' => 'getSumTxsOut7Gaming',
        'sum_txs_out_7_gambling' => 'getSumTxsOut7Gambling',
        'max_balance_forever_onchain' => 'getMaxBalanceForeverOnchain',
        'max_balance_forever_nft' => 'getMaxBalanceForeverNft',
        'max_balance_forever_gaming' => 'getMaxBalanceForeverGaming',
        'max_balance_forever_gambling' => 'getMaxBalanceForeverGambling',
        'max_balance_365_onchain' => 'getMaxBalance365Onchain',
        'max_balance_365_nft' => 'getMaxBalance365Nft',
        'max_balance_365_gaming' => 'getMaxBalance365Gaming',
        'max_balance_365_gambling' => 'getMaxBalance365Gambling',
        'max_balance_31_60_onchain' => 'getMaxBalance3160Onchain',
        'max_balance_31_60_nft' => 'getMaxBalance3160Nft',
        'max_balance_31_60_gaming' => 'getMaxBalance3160Gaming',
        'max_balance_31_60_gambling' => 'getMaxBalance3160Gambling',
        'max_balance_30_onchain' => 'getMaxBalance30Onchain',
        'max_balance_30_nft' => 'getMaxBalance30Nft',
        'max_balance_30_gaming' => 'getMaxBalance30Gaming',
        'max_balance_30_gambling' => 'getMaxBalance30Gambling',
        'max_balance_7_onchain' => 'getMaxBalance7Onchain',
        'max_balance_7_nft' => 'getMaxBalance7Nft',
        'max_balance_7_gaming' => 'getMaxBalance7Gaming',
        'max_balance_7_gambling' => 'getMaxBalance7Gambling'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sum_txs_all_forever_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_all_forever_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_all_forever_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_all_forever_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_all_365_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_all_365_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_all_365_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_all_365_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_all_31_60_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_all_31_60_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_all_31_60_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_all_31_60_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_all_30_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_all_30_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_all_30_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_all_30_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_all_7_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_all_7_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_all_7_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_all_7_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_in_forever_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_in_forever_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_in_forever_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_in_forever_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_in_365_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_in_365_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_in_365_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_in_365_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_in_31_60_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_in_31_60_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_in_31_60_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_in_31_60_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_in_30_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_in_30_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_in_30_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_in_30_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_in_7_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_in_7_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_in_7_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_in_7_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_out_forever_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_out_forever_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_out_forever_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_out_forever_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_out_365_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_out_365_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_out_365_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_out_365_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_out_31_60_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_out_31_60_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_out_31_60_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_out_31_60_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_out_30_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_out_30_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_out_30_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_out_30_gambling', $data ?? [], null);
        $this->setIfExists('sum_txs_out_7_onchain', $data ?? [], null);
        $this->setIfExists('sum_txs_out_7_nft', $data ?? [], null);
        $this->setIfExists('sum_txs_out_7_gaming', $data ?? [], null);
        $this->setIfExists('sum_txs_out_7_gambling', $data ?? [], null);
        $this->setIfExists('max_balance_forever_onchain', $data ?? [], null);
        $this->setIfExists('max_balance_forever_nft', $data ?? [], null);
        $this->setIfExists('max_balance_forever_gaming', $data ?? [], null);
        $this->setIfExists('max_balance_forever_gambling', $data ?? [], null);
        $this->setIfExists('max_balance_365_onchain', $data ?? [], null);
        $this->setIfExists('max_balance_365_nft', $data ?? [], null);
        $this->setIfExists('max_balance_365_gaming', $data ?? [], null);
        $this->setIfExists('max_balance_365_gambling', $data ?? [], null);
        $this->setIfExists('max_balance_31_60_onchain', $data ?? [], null);
        $this->setIfExists('max_balance_31_60_nft', $data ?? [], null);
        $this->setIfExists('max_balance_31_60_gaming', $data ?? [], null);
        $this->setIfExists('max_balance_31_60_gambling', $data ?? [], null);
        $this->setIfExists('max_balance_30_onchain', $data ?? [], null);
        $this->setIfExists('max_balance_30_nft', $data ?? [], null);
        $this->setIfExists('max_balance_30_gaming', $data ?? [], null);
        $this->setIfExists('max_balance_30_gambling', $data ?? [], null);
        $this->setIfExists('max_balance_7_onchain', $data ?? [], null);
        $this->setIfExists('max_balance_7_nft', $data ?? [], null);
        $this->setIfExists('max_balance_7_gaming', $data ?? [], null);
        $this->setIfExists('max_balance_7_gambling', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sum_txs_all_forever_onchain
     *
     * @return float|null
     */
    public function getSumTxsAllForeverOnchain()
    {
        return $this->container['sum_txs_all_forever_onchain'];
    }

    /**
     * Sets sum_txs_all_forever_onchain
     *
     * @param float|null $sum_txs_all_forever_onchain Sum of all transactions
     *
     * @return self
     */
    public function setSumTxsAllForeverOnchain($sum_txs_all_forever_onchain)
    {

        if (is_null($sum_txs_all_forever_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_forever_onchain cannot be null');
        }

        $this->container['sum_txs_all_forever_onchain'] = $sum_txs_all_forever_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_all_forever_nft
     *
     * @return float|null
     */
    public function getSumTxsAllForeverNft()
    {
        return $this->container['sum_txs_all_forever_nft'];
    }

    /**
     * Sets sum_txs_all_forever_nft
     *
     * @param float|null $sum_txs_all_forever_nft Sum of all NFT transactions
     *
     * @return self
     */
    public function setSumTxsAllForeverNft($sum_txs_all_forever_nft)
    {

        if (is_null($sum_txs_all_forever_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_forever_nft cannot be null');
        }

        $this->container['sum_txs_all_forever_nft'] = $sum_txs_all_forever_nft;

        return $this;
    }

    /**
     * Gets sum_txs_all_forever_gaming
     *
     * @return float|null
     */
    public function getSumTxsAllForeverGaming()
    {
        return $this->container['sum_txs_all_forever_gaming'];
    }

    /**
     * Sets sum_txs_all_forever_gaming
     *
     * @param float|null $sum_txs_all_forever_gaming Sum of all gaming transactions
     *
     * @return self
     */
    public function setSumTxsAllForeverGaming($sum_txs_all_forever_gaming)
    {

        if (is_null($sum_txs_all_forever_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_forever_gaming cannot be null');
        }

        $this->container['sum_txs_all_forever_gaming'] = $sum_txs_all_forever_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_all_forever_gambling
     *
     * @return float|null
     */
    public function getSumTxsAllForeverGambling()
    {
        return $this->container['sum_txs_all_forever_gambling'];
    }

    /**
     * Sets sum_txs_all_forever_gambling
     *
     * @param float|null $sum_txs_all_forever_gambling Sum of all gambling transactions
     *
     * @return self
     */
    public function setSumTxsAllForeverGambling($sum_txs_all_forever_gambling)
    {

        if (is_null($sum_txs_all_forever_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_forever_gambling cannot be null');
        }

        $this->container['sum_txs_all_forever_gambling'] = $sum_txs_all_forever_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_all_365_onchain
     *
     * @return float|null
     */
    public function getSumTxsAll365Onchain()
    {
        return $this->container['sum_txs_all_365_onchain'];
    }

    /**
     * Sets sum_txs_all_365_onchain
     *
     * @param float|null $sum_txs_all_365_onchain Sum of all transactions during last year
     *
     * @return self
     */
    public function setSumTxsAll365Onchain($sum_txs_all_365_onchain)
    {

        if (is_null($sum_txs_all_365_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_365_onchain cannot be null');
        }

        $this->container['sum_txs_all_365_onchain'] = $sum_txs_all_365_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_all_365_nft
     *
     * @return float|null
     */
    public function getSumTxsAll365Nft()
    {
        return $this->container['sum_txs_all_365_nft'];
    }

    /**
     * Sets sum_txs_all_365_nft
     *
     * @param float|null $sum_txs_all_365_nft Sum of all NFT transactions during last year
     *
     * @return self
     */
    public function setSumTxsAll365Nft($sum_txs_all_365_nft)
    {

        if (is_null($sum_txs_all_365_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_365_nft cannot be null');
        }

        $this->container['sum_txs_all_365_nft'] = $sum_txs_all_365_nft;

        return $this;
    }

    /**
     * Gets sum_txs_all_365_gaming
     *
     * @return float|null
     */
    public function getSumTxsAll365Gaming()
    {
        return $this->container['sum_txs_all_365_gaming'];
    }

    /**
     * Sets sum_txs_all_365_gaming
     *
     * @param float|null $sum_txs_all_365_gaming Sum of all gaming transactions during last year
     *
     * @return self
     */
    public function setSumTxsAll365Gaming($sum_txs_all_365_gaming)
    {

        if (is_null($sum_txs_all_365_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_365_gaming cannot be null');
        }

        $this->container['sum_txs_all_365_gaming'] = $sum_txs_all_365_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_all_365_gambling
     *
     * @return float|null
     */
    public function getSumTxsAll365Gambling()
    {
        return $this->container['sum_txs_all_365_gambling'];
    }

    /**
     * Sets sum_txs_all_365_gambling
     *
     * @param float|null $sum_txs_all_365_gambling Sum of all gambling transactions during last year
     *
     * @return self
     */
    public function setSumTxsAll365Gambling($sum_txs_all_365_gambling)
    {

        if (is_null($sum_txs_all_365_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_365_gambling cannot be null');
        }

        $this->container['sum_txs_all_365_gambling'] = $sum_txs_all_365_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_all_31_60_onchain
     *
     * @return float|null
     */
    public function getSumTxsAll3160Onchain()
    {
        return $this->container['sum_txs_all_31_60_onchain'];
    }

    /**
     * Sets sum_txs_all_31_60_onchain
     *
     * @param float|null $sum_txs_all_31_60_onchain Sum of all transactions during previous month
     *
     * @return self
     */
    public function setSumTxsAll3160Onchain($sum_txs_all_31_60_onchain)
    {

        if (is_null($sum_txs_all_31_60_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_31_60_onchain cannot be null');
        }

        $this->container['sum_txs_all_31_60_onchain'] = $sum_txs_all_31_60_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_all_31_60_nft
     *
     * @return float|null
     */
    public function getSumTxsAll3160Nft()
    {
        return $this->container['sum_txs_all_31_60_nft'];
    }

    /**
     * Sets sum_txs_all_31_60_nft
     *
     * @param float|null $sum_txs_all_31_60_nft Sum of all NFT transactions during previous month
     *
     * @return self
     */
    public function setSumTxsAll3160Nft($sum_txs_all_31_60_nft)
    {

        if (is_null($sum_txs_all_31_60_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_31_60_nft cannot be null');
        }

        $this->container['sum_txs_all_31_60_nft'] = $sum_txs_all_31_60_nft;

        return $this;
    }

    /**
     * Gets sum_txs_all_31_60_gaming
     *
     * @return float|null
     */
    public function getSumTxsAll3160Gaming()
    {
        return $this->container['sum_txs_all_31_60_gaming'];
    }

    /**
     * Sets sum_txs_all_31_60_gaming
     *
     * @param float|null $sum_txs_all_31_60_gaming Sum of all gaming transactions during previous month
     *
     * @return self
     */
    public function setSumTxsAll3160Gaming($sum_txs_all_31_60_gaming)
    {

        if (is_null($sum_txs_all_31_60_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_31_60_gaming cannot be null');
        }

        $this->container['sum_txs_all_31_60_gaming'] = $sum_txs_all_31_60_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_all_31_60_gambling
     *
     * @return float|null
     */
    public function getSumTxsAll3160Gambling()
    {
        return $this->container['sum_txs_all_31_60_gambling'];
    }

    /**
     * Sets sum_txs_all_31_60_gambling
     *
     * @param float|null $sum_txs_all_31_60_gambling Sum of all gambling transactions during previous month
     *
     * @return self
     */
    public function setSumTxsAll3160Gambling($sum_txs_all_31_60_gambling)
    {

        if (is_null($sum_txs_all_31_60_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_31_60_gambling cannot be null');
        }

        $this->container['sum_txs_all_31_60_gambling'] = $sum_txs_all_31_60_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_all_30_onchain
     *
     * @return float|null
     */
    public function getSumTxsAll30Onchain()
    {
        return $this->container['sum_txs_all_30_onchain'];
    }

    /**
     * Sets sum_txs_all_30_onchain
     *
     * @param float|null $sum_txs_all_30_onchain Sum of all transactions during last month
     *
     * @return self
     */
    public function setSumTxsAll30Onchain($sum_txs_all_30_onchain)
    {

        if (is_null($sum_txs_all_30_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_30_onchain cannot be null');
        }

        $this->container['sum_txs_all_30_onchain'] = $sum_txs_all_30_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_all_30_nft
     *
     * @return float|null
     */
    public function getSumTxsAll30Nft()
    {
        return $this->container['sum_txs_all_30_nft'];
    }

    /**
     * Sets sum_txs_all_30_nft
     *
     * @param float|null $sum_txs_all_30_nft Sum of all NFT transactions during last month
     *
     * @return self
     */
    public function setSumTxsAll30Nft($sum_txs_all_30_nft)
    {

        if (is_null($sum_txs_all_30_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_30_nft cannot be null');
        }

        $this->container['sum_txs_all_30_nft'] = $sum_txs_all_30_nft;

        return $this;
    }

    /**
     * Gets sum_txs_all_30_gaming
     *
     * @return float|null
     */
    public function getSumTxsAll30Gaming()
    {
        return $this->container['sum_txs_all_30_gaming'];
    }

    /**
     * Sets sum_txs_all_30_gaming
     *
     * @param float|null $sum_txs_all_30_gaming Sum of all gaming transactions during last month
     *
     * @return self
     */
    public function setSumTxsAll30Gaming($sum_txs_all_30_gaming)
    {

        if (is_null($sum_txs_all_30_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_30_gaming cannot be null');
        }

        $this->container['sum_txs_all_30_gaming'] = $sum_txs_all_30_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_all_30_gambling
     *
     * @return float|null
     */
    public function getSumTxsAll30Gambling()
    {
        return $this->container['sum_txs_all_30_gambling'];
    }

    /**
     * Sets sum_txs_all_30_gambling
     *
     * @param float|null $sum_txs_all_30_gambling Sum of all gambling transactions during last month
     *
     * @return self
     */
    public function setSumTxsAll30Gambling($sum_txs_all_30_gambling)
    {

        if (is_null($sum_txs_all_30_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_30_gambling cannot be null');
        }

        $this->container['sum_txs_all_30_gambling'] = $sum_txs_all_30_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_all_7_onchain
     *
     * @return float|null
     */
    public function getSumTxsAll7Onchain()
    {
        return $this->container['sum_txs_all_7_onchain'];
    }

    /**
     * Sets sum_txs_all_7_onchain
     *
     * @param float|null $sum_txs_all_7_onchain Sum of all transactions during last week
     *
     * @return self
     */
    public function setSumTxsAll7Onchain($sum_txs_all_7_onchain)
    {

        if (is_null($sum_txs_all_7_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_7_onchain cannot be null');
        }

        $this->container['sum_txs_all_7_onchain'] = $sum_txs_all_7_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_all_7_nft
     *
     * @return float|null
     */
    public function getSumTxsAll7Nft()
    {
        return $this->container['sum_txs_all_7_nft'];
    }

    /**
     * Sets sum_txs_all_7_nft
     *
     * @param float|null $sum_txs_all_7_nft Sum of all NFT transactions during last week
     *
     * @return self
     */
    public function setSumTxsAll7Nft($sum_txs_all_7_nft)
    {

        if (is_null($sum_txs_all_7_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_7_nft cannot be null');
        }

        $this->container['sum_txs_all_7_nft'] = $sum_txs_all_7_nft;

        return $this;
    }

    /**
     * Gets sum_txs_all_7_gaming
     *
     * @return float|null
     */
    public function getSumTxsAll7Gaming()
    {
        return $this->container['sum_txs_all_7_gaming'];
    }

    /**
     * Sets sum_txs_all_7_gaming
     *
     * @param float|null $sum_txs_all_7_gaming Sum of all gaming transactions during last week
     *
     * @return self
     */
    public function setSumTxsAll7Gaming($sum_txs_all_7_gaming)
    {

        if (is_null($sum_txs_all_7_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_7_gaming cannot be null');
        }

        $this->container['sum_txs_all_7_gaming'] = $sum_txs_all_7_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_all_7_gambling
     *
     * @return float|null
     */
    public function getSumTxsAll7Gambling()
    {
        return $this->container['sum_txs_all_7_gambling'];
    }

    /**
     * Sets sum_txs_all_7_gambling
     *
     * @param float|null $sum_txs_all_7_gambling Sum of all gambling transactions during last week
     *
     * @return self
     */
    public function setSumTxsAll7Gambling($sum_txs_all_7_gambling)
    {

        if (is_null($sum_txs_all_7_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_all_7_gambling cannot be null');
        }

        $this->container['sum_txs_all_7_gambling'] = $sum_txs_all_7_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_in_forever_onchain
     *
     * @return float|null
     */
    public function getSumTxsInForeverOnchain()
    {
        return $this->container['sum_txs_in_forever_onchain'];
    }

    /**
     * Sets sum_txs_in_forever_onchain
     *
     * @param float|null $sum_txs_in_forever_onchain Sum of all IN transactions
     *
     * @return self
     */
    public function setSumTxsInForeverOnchain($sum_txs_in_forever_onchain)
    {

        if (is_null($sum_txs_in_forever_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_forever_onchain cannot be null');
        }

        $this->container['sum_txs_in_forever_onchain'] = $sum_txs_in_forever_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_in_forever_nft
     *
     * @return float|null
     */
    public function getSumTxsInForeverNft()
    {
        return $this->container['sum_txs_in_forever_nft'];
    }

    /**
     * Sets sum_txs_in_forever_nft
     *
     * @param float|null $sum_txs_in_forever_nft Sum of all IN NFT transactions
     *
     * @return self
     */
    public function setSumTxsInForeverNft($sum_txs_in_forever_nft)
    {

        if (is_null($sum_txs_in_forever_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_forever_nft cannot be null');
        }

        $this->container['sum_txs_in_forever_nft'] = $sum_txs_in_forever_nft;

        return $this;
    }

    /**
     * Gets sum_txs_in_forever_gaming
     *
     * @return float|null
     */
    public function getSumTxsInForeverGaming()
    {
        return $this->container['sum_txs_in_forever_gaming'];
    }

    /**
     * Sets sum_txs_in_forever_gaming
     *
     * @param float|null $sum_txs_in_forever_gaming Sum of all IN gaming transactions
     *
     * @return self
     */
    public function setSumTxsInForeverGaming($sum_txs_in_forever_gaming)
    {

        if (is_null($sum_txs_in_forever_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_forever_gaming cannot be null');
        }

        $this->container['sum_txs_in_forever_gaming'] = $sum_txs_in_forever_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_in_forever_gambling
     *
     * @return float|null
     */
    public function getSumTxsInForeverGambling()
    {
        return $this->container['sum_txs_in_forever_gambling'];
    }

    /**
     * Sets sum_txs_in_forever_gambling
     *
     * @param float|null $sum_txs_in_forever_gambling Sum of all IN gambling transactions
     *
     * @return self
     */
    public function setSumTxsInForeverGambling($sum_txs_in_forever_gambling)
    {

        if (is_null($sum_txs_in_forever_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_forever_gambling cannot be null');
        }

        $this->container['sum_txs_in_forever_gambling'] = $sum_txs_in_forever_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_in_365_onchain
     *
     * @return float|null
     */
    public function getSumTxsIn365Onchain()
    {
        return $this->container['sum_txs_in_365_onchain'];
    }

    /**
     * Sets sum_txs_in_365_onchain
     *
     * @param float|null $sum_txs_in_365_onchain Sum of all IN transactions during last year
     *
     * @return self
     */
    public function setSumTxsIn365Onchain($sum_txs_in_365_onchain)
    {

        if (is_null($sum_txs_in_365_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_365_onchain cannot be null');
        }

        $this->container['sum_txs_in_365_onchain'] = $sum_txs_in_365_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_in_365_nft
     *
     * @return float|null
     */
    public function getSumTxsIn365Nft()
    {
        return $this->container['sum_txs_in_365_nft'];
    }

    /**
     * Sets sum_txs_in_365_nft
     *
     * @param float|null $sum_txs_in_365_nft Sum of all IN NFT transactions during last year
     *
     * @return self
     */
    public function setSumTxsIn365Nft($sum_txs_in_365_nft)
    {

        if (is_null($sum_txs_in_365_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_365_nft cannot be null');
        }

        $this->container['sum_txs_in_365_nft'] = $sum_txs_in_365_nft;

        return $this;
    }

    /**
     * Gets sum_txs_in_365_gaming
     *
     * @return float|null
     */
    public function getSumTxsIn365Gaming()
    {
        return $this->container['sum_txs_in_365_gaming'];
    }

    /**
     * Sets sum_txs_in_365_gaming
     *
     * @param float|null $sum_txs_in_365_gaming Sum of all IN gaming transactions during last year
     *
     * @return self
     */
    public function setSumTxsIn365Gaming($sum_txs_in_365_gaming)
    {

        if (is_null($sum_txs_in_365_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_365_gaming cannot be null');
        }

        $this->container['sum_txs_in_365_gaming'] = $sum_txs_in_365_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_in_365_gambling
     *
     * @return float|null
     */
    public function getSumTxsIn365Gambling()
    {
        return $this->container['sum_txs_in_365_gambling'];
    }

    /**
     * Sets sum_txs_in_365_gambling
     *
     * @param float|null $sum_txs_in_365_gambling Sum of all IN gambling transactions during last year
     *
     * @return self
     */
    public function setSumTxsIn365Gambling($sum_txs_in_365_gambling)
    {

        if (is_null($sum_txs_in_365_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_365_gambling cannot be null');
        }

        $this->container['sum_txs_in_365_gambling'] = $sum_txs_in_365_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_in_31_60_onchain
     *
     * @return float|null
     */
    public function getSumTxsIn3160Onchain()
    {
        return $this->container['sum_txs_in_31_60_onchain'];
    }

    /**
     * Sets sum_txs_in_31_60_onchain
     *
     * @param float|null $sum_txs_in_31_60_onchain Sum of all IN transactions during previous month
     *
     * @return self
     */
    public function setSumTxsIn3160Onchain($sum_txs_in_31_60_onchain)
    {

        if (is_null($sum_txs_in_31_60_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_31_60_onchain cannot be null');
        }

        $this->container['sum_txs_in_31_60_onchain'] = $sum_txs_in_31_60_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_in_31_60_nft
     *
     * @return float|null
     */
    public function getSumTxsIn3160Nft()
    {
        return $this->container['sum_txs_in_31_60_nft'];
    }

    /**
     * Sets sum_txs_in_31_60_nft
     *
     * @param float|null $sum_txs_in_31_60_nft Sum of all IN NFT transactions during previous month
     *
     * @return self
     */
    public function setSumTxsIn3160Nft($sum_txs_in_31_60_nft)
    {

        if (is_null($sum_txs_in_31_60_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_31_60_nft cannot be null');
        }

        $this->container['sum_txs_in_31_60_nft'] = $sum_txs_in_31_60_nft;

        return $this;
    }

    /**
     * Gets sum_txs_in_31_60_gaming
     *
     * @return float|null
     */
    public function getSumTxsIn3160Gaming()
    {
        return $this->container['sum_txs_in_31_60_gaming'];
    }

    /**
     * Sets sum_txs_in_31_60_gaming
     *
     * @param float|null $sum_txs_in_31_60_gaming Sum of all IN gaming transactions during previous month
     *
     * @return self
     */
    public function setSumTxsIn3160Gaming($sum_txs_in_31_60_gaming)
    {

        if (is_null($sum_txs_in_31_60_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_31_60_gaming cannot be null');
        }

        $this->container['sum_txs_in_31_60_gaming'] = $sum_txs_in_31_60_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_in_31_60_gambling
     *
     * @return float|null
     */
    public function getSumTxsIn3160Gambling()
    {
        return $this->container['sum_txs_in_31_60_gambling'];
    }

    /**
     * Sets sum_txs_in_31_60_gambling
     *
     * @param float|null $sum_txs_in_31_60_gambling Sum of all IN gambling transactions during previous month
     *
     * @return self
     */
    public function setSumTxsIn3160Gambling($sum_txs_in_31_60_gambling)
    {

        if (is_null($sum_txs_in_31_60_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_31_60_gambling cannot be null');
        }

        $this->container['sum_txs_in_31_60_gambling'] = $sum_txs_in_31_60_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_in_30_onchain
     *
     * @return float|null
     */
    public function getSumTxsIn30Onchain()
    {
        return $this->container['sum_txs_in_30_onchain'];
    }

    /**
     * Sets sum_txs_in_30_onchain
     *
     * @param float|null $sum_txs_in_30_onchain Sum of all IN transactions during last month
     *
     * @return self
     */
    public function setSumTxsIn30Onchain($sum_txs_in_30_onchain)
    {

        if (is_null($sum_txs_in_30_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_30_onchain cannot be null');
        }

        $this->container['sum_txs_in_30_onchain'] = $sum_txs_in_30_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_in_30_nft
     *
     * @return float|null
     */
    public function getSumTxsIn30Nft()
    {
        return $this->container['sum_txs_in_30_nft'];
    }

    /**
     * Sets sum_txs_in_30_nft
     *
     * @param float|null $sum_txs_in_30_nft Sum of all IN NFT transactions during last month
     *
     * @return self
     */
    public function setSumTxsIn30Nft($sum_txs_in_30_nft)
    {

        if (is_null($sum_txs_in_30_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_30_nft cannot be null');
        }

        $this->container['sum_txs_in_30_nft'] = $sum_txs_in_30_nft;

        return $this;
    }

    /**
     * Gets sum_txs_in_30_gaming
     *
     * @return float|null
     */
    public function getSumTxsIn30Gaming()
    {
        return $this->container['sum_txs_in_30_gaming'];
    }

    /**
     * Sets sum_txs_in_30_gaming
     *
     * @param float|null $sum_txs_in_30_gaming Sum of all IN gaming transactions during last month
     *
     * @return self
     */
    public function setSumTxsIn30Gaming($sum_txs_in_30_gaming)
    {

        if (is_null($sum_txs_in_30_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_30_gaming cannot be null');
        }

        $this->container['sum_txs_in_30_gaming'] = $sum_txs_in_30_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_in_30_gambling
     *
     * @return float|null
     */
    public function getSumTxsIn30Gambling()
    {
        return $this->container['sum_txs_in_30_gambling'];
    }

    /**
     * Sets sum_txs_in_30_gambling
     *
     * @param float|null $sum_txs_in_30_gambling Sum of all IN gambling transactions during last month
     *
     * @return self
     */
    public function setSumTxsIn30Gambling($sum_txs_in_30_gambling)
    {

        if (is_null($sum_txs_in_30_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_30_gambling cannot be null');
        }

        $this->container['sum_txs_in_30_gambling'] = $sum_txs_in_30_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_in_7_onchain
     *
     * @return float|null
     */
    public function getSumTxsIn7Onchain()
    {
        return $this->container['sum_txs_in_7_onchain'];
    }

    /**
     * Sets sum_txs_in_7_onchain
     *
     * @param float|null $sum_txs_in_7_onchain Sum of all IN transactions during last week
     *
     * @return self
     */
    public function setSumTxsIn7Onchain($sum_txs_in_7_onchain)
    {

        if (is_null($sum_txs_in_7_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_7_onchain cannot be null');
        }

        $this->container['sum_txs_in_7_onchain'] = $sum_txs_in_7_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_in_7_nft
     *
     * @return float|null
     */
    public function getSumTxsIn7Nft()
    {
        return $this->container['sum_txs_in_7_nft'];
    }

    /**
     * Sets sum_txs_in_7_nft
     *
     * @param float|null $sum_txs_in_7_nft Sum of all IN NFT transactions during last week
     *
     * @return self
     */
    public function setSumTxsIn7Nft($sum_txs_in_7_nft)
    {

        if (is_null($sum_txs_in_7_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_7_nft cannot be null');
        }

        $this->container['sum_txs_in_7_nft'] = $sum_txs_in_7_nft;

        return $this;
    }

    /**
     * Gets sum_txs_in_7_gaming
     *
     * @return float|null
     */
    public function getSumTxsIn7Gaming()
    {
        return $this->container['sum_txs_in_7_gaming'];
    }

    /**
     * Sets sum_txs_in_7_gaming
     *
     * @param float|null $sum_txs_in_7_gaming Sum of all IN gaming transactions during last week
     *
     * @return self
     */
    public function setSumTxsIn7Gaming($sum_txs_in_7_gaming)
    {

        if (is_null($sum_txs_in_7_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_7_gaming cannot be null');
        }

        $this->container['sum_txs_in_7_gaming'] = $sum_txs_in_7_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_in_7_gambling
     *
     * @return float|null
     */
    public function getSumTxsIn7Gambling()
    {
        return $this->container['sum_txs_in_7_gambling'];
    }

    /**
     * Sets sum_txs_in_7_gambling
     *
     * @param float|null $sum_txs_in_7_gambling Sum of all IN gambling transactions during last week
     *
     * @return self
     */
    public function setSumTxsIn7Gambling($sum_txs_in_7_gambling)
    {

        if (is_null($sum_txs_in_7_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_in_7_gambling cannot be null');
        }

        $this->container['sum_txs_in_7_gambling'] = $sum_txs_in_7_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_out_forever_onchain
     *
     * @return float|null
     */
    public function getSumTxsOutForeverOnchain()
    {
        return $this->container['sum_txs_out_forever_onchain'];
    }

    /**
     * Sets sum_txs_out_forever_onchain
     *
     * @param float|null $sum_txs_out_forever_onchain Sum of all OUT transactions
     *
     * @return self
     */
    public function setSumTxsOutForeverOnchain($sum_txs_out_forever_onchain)
    {

        if (is_null($sum_txs_out_forever_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_forever_onchain cannot be null');
        }

        $this->container['sum_txs_out_forever_onchain'] = $sum_txs_out_forever_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_out_forever_nft
     *
     * @return float|null
     */
    public function getSumTxsOutForeverNft()
    {
        return $this->container['sum_txs_out_forever_nft'];
    }

    /**
     * Sets sum_txs_out_forever_nft
     *
     * @param float|null $sum_txs_out_forever_nft Sum of all OUT NFT transactions
     *
     * @return self
     */
    public function setSumTxsOutForeverNft($sum_txs_out_forever_nft)
    {

        if (is_null($sum_txs_out_forever_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_forever_nft cannot be null');
        }

        $this->container['sum_txs_out_forever_nft'] = $sum_txs_out_forever_nft;

        return $this;
    }

    /**
     * Gets sum_txs_out_forever_gaming
     *
     * @return float|null
     */
    public function getSumTxsOutForeverGaming()
    {
        return $this->container['sum_txs_out_forever_gaming'];
    }

    /**
     * Sets sum_txs_out_forever_gaming
     *
     * @param float|null $sum_txs_out_forever_gaming Sum of all OUT gaming transactions
     *
     * @return self
     */
    public function setSumTxsOutForeverGaming($sum_txs_out_forever_gaming)
    {

        if (is_null($sum_txs_out_forever_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_forever_gaming cannot be null');
        }

        $this->container['sum_txs_out_forever_gaming'] = $sum_txs_out_forever_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_out_forever_gambling
     *
     * @return float|null
     */
    public function getSumTxsOutForeverGambling()
    {
        return $this->container['sum_txs_out_forever_gambling'];
    }

    /**
     * Sets sum_txs_out_forever_gambling
     *
     * @param float|null $sum_txs_out_forever_gambling Sum of all OUT gambling transactions
     *
     * @return self
     */
    public function setSumTxsOutForeverGambling($sum_txs_out_forever_gambling)
    {

        if (is_null($sum_txs_out_forever_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_forever_gambling cannot be null');
        }

        $this->container['sum_txs_out_forever_gambling'] = $sum_txs_out_forever_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_out_365_onchain
     *
     * @return float|null
     */
    public function getSumTxsOut365Onchain()
    {
        return $this->container['sum_txs_out_365_onchain'];
    }

    /**
     * Sets sum_txs_out_365_onchain
     *
     * @param float|null $sum_txs_out_365_onchain Sum of all OUT transactions during last year
     *
     * @return self
     */
    public function setSumTxsOut365Onchain($sum_txs_out_365_onchain)
    {

        if (is_null($sum_txs_out_365_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_365_onchain cannot be null');
        }

        $this->container['sum_txs_out_365_onchain'] = $sum_txs_out_365_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_out_365_nft
     *
     * @return float|null
     */
    public function getSumTxsOut365Nft()
    {
        return $this->container['sum_txs_out_365_nft'];
    }

    /**
     * Sets sum_txs_out_365_nft
     *
     * @param float|null $sum_txs_out_365_nft Sum of all OUT NFT transactions during last year
     *
     * @return self
     */
    public function setSumTxsOut365Nft($sum_txs_out_365_nft)
    {

        if (is_null($sum_txs_out_365_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_365_nft cannot be null');
        }

        $this->container['sum_txs_out_365_nft'] = $sum_txs_out_365_nft;

        return $this;
    }

    /**
     * Gets sum_txs_out_365_gaming
     *
     * @return float|null
     */
    public function getSumTxsOut365Gaming()
    {
        return $this->container['sum_txs_out_365_gaming'];
    }

    /**
     * Sets sum_txs_out_365_gaming
     *
     * @param float|null $sum_txs_out_365_gaming Sum of all OUT gaming transactions during last year
     *
     * @return self
     */
    public function setSumTxsOut365Gaming($sum_txs_out_365_gaming)
    {

        if (is_null($sum_txs_out_365_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_365_gaming cannot be null');
        }

        $this->container['sum_txs_out_365_gaming'] = $sum_txs_out_365_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_out_365_gambling
     *
     * @return float|null
     */
    public function getSumTxsOut365Gambling()
    {
        return $this->container['sum_txs_out_365_gambling'];
    }

    /**
     * Sets sum_txs_out_365_gambling
     *
     * @param float|null $sum_txs_out_365_gambling Sum of all OUT gambling transactions during last year
     *
     * @return self
     */
    public function setSumTxsOut365Gambling($sum_txs_out_365_gambling)
    {

        if (is_null($sum_txs_out_365_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_365_gambling cannot be null');
        }

        $this->container['sum_txs_out_365_gambling'] = $sum_txs_out_365_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_out_31_60_onchain
     *
     * @return float|null
     */
    public function getSumTxsOut3160Onchain()
    {
        return $this->container['sum_txs_out_31_60_onchain'];
    }

    /**
     * Sets sum_txs_out_31_60_onchain
     *
     * @param float|null $sum_txs_out_31_60_onchain Sum of all OUT transactions during previous month
     *
     * @return self
     */
    public function setSumTxsOut3160Onchain($sum_txs_out_31_60_onchain)
    {

        if (is_null($sum_txs_out_31_60_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_31_60_onchain cannot be null');
        }

        $this->container['sum_txs_out_31_60_onchain'] = $sum_txs_out_31_60_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_out_31_60_nft
     *
     * @return float|null
     */
    public function getSumTxsOut3160Nft()
    {
        return $this->container['sum_txs_out_31_60_nft'];
    }

    /**
     * Sets sum_txs_out_31_60_nft
     *
     * @param float|null $sum_txs_out_31_60_nft Sum of all OUT NFT transactions during previous month
     *
     * @return self
     */
    public function setSumTxsOut3160Nft($sum_txs_out_31_60_nft)
    {

        if (is_null($sum_txs_out_31_60_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_31_60_nft cannot be null');
        }

        $this->container['sum_txs_out_31_60_nft'] = $sum_txs_out_31_60_nft;

        return $this;
    }

    /**
     * Gets sum_txs_out_31_60_gaming
     *
     * @return float|null
     */
    public function getSumTxsOut3160Gaming()
    {
        return $this->container['sum_txs_out_31_60_gaming'];
    }

    /**
     * Sets sum_txs_out_31_60_gaming
     *
     * @param float|null $sum_txs_out_31_60_gaming Sum of all OUT gaming transactions during previous month
     *
     * @return self
     */
    public function setSumTxsOut3160Gaming($sum_txs_out_31_60_gaming)
    {

        if (is_null($sum_txs_out_31_60_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_31_60_gaming cannot be null');
        }

        $this->container['sum_txs_out_31_60_gaming'] = $sum_txs_out_31_60_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_out_31_60_gambling
     *
     * @return float|null
     */
    public function getSumTxsOut3160Gambling()
    {
        return $this->container['sum_txs_out_31_60_gambling'];
    }

    /**
     * Sets sum_txs_out_31_60_gambling
     *
     * @param float|null $sum_txs_out_31_60_gambling Sum of all OUT gambling transactions during previous month
     *
     * @return self
     */
    public function setSumTxsOut3160Gambling($sum_txs_out_31_60_gambling)
    {

        if (is_null($sum_txs_out_31_60_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_31_60_gambling cannot be null');
        }

        $this->container['sum_txs_out_31_60_gambling'] = $sum_txs_out_31_60_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_out_30_onchain
     *
     * @return float|null
     */
    public function getSumTxsOut30Onchain()
    {
        return $this->container['sum_txs_out_30_onchain'];
    }

    /**
     * Sets sum_txs_out_30_onchain
     *
     * @param float|null $sum_txs_out_30_onchain Sum of all OUT transactions during last month
     *
     * @return self
     */
    public function setSumTxsOut30Onchain($sum_txs_out_30_onchain)
    {

        if (is_null($sum_txs_out_30_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_30_onchain cannot be null');
        }

        $this->container['sum_txs_out_30_onchain'] = $sum_txs_out_30_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_out_30_nft
     *
     * @return float|null
     */
    public function getSumTxsOut30Nft()
    {
        return $this->container['sum_txs_out_30_nft'];
    }

    /**
     * Sets sum_txs_out_30_nft
     *
     * @param float|null $sum_txs_out_30_nft Sum of all OUT NFT transactions during last month
     *
     * @return self
     */
    public function setSumTxsOut30Nft($sum_txs_out_30_nft)
    {

        if (is_null($sum_txs_out_30_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_30_nft cannot be null');
        }

        $this->container['sum_txs_out_30_nft'] = $sum_txs_out_30_nft;

        return $this;
    }

    /**
     * Gets sum_txs_out_30_gaming
     *
     * @return float|null
     */
    public function getSumTxsOut30Gaming()
    {
        return $this->container['sum_txs_out_30_gaming'];
    }

    /**
     * Sets sum_txs_out_30_gaming
     *
     * @param float|null $sum_txs_out_30_gaming Sum of all OUT gaming transactions during last month
     *
     * @return self
     */
    public function setSumTxsOut30Gaming($sum_txs_out_30_gaming)
    {

        if (is_null($sum_txs_out_30_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_30_gaming cannot be null');
        }

        $this->container['sum_txs_out_30_gaming'] = $sum_txs_out_30_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_out_30_gambling
     *
     * @return float|null
     */
    public function getSumTxsOut30Gambling()
    {
        return $this->container['sum_txs_out_30_gambling'];
    }

    /**
     * Sets sum_txs_out_30_gambling
     *
     * @param float|null $sum_txs_out_30_gambling Sum of all OUT gambling transactions during last month
     *
     * @return self
     */
    public function setSumTxsOut30Gambling($sum_txs_out_30_gambling)
    {

        if (is_null($sum_txs_out_30_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_30_gambling cannot be null');
        }

        $this->container['sum_txs_out_30_gambling'] = $sum_txs_out_30_gambling;

        return $this;
    }

    /**
     * Gets sum_txs_out_7_onchain
     *
     * @return float|null
     */
    public function getSumTxsOut7Onchain()
    {
        return $this->container['sum_txs_out_7_onchain'];
    }

    /**
     * Sets sum_txs_out_7_onchain
     *
     * @param float|null $sum_txs_out_7_onchain Sum of all OUT transactions during last week
     *
     * @return self
     */
    public function setSumTxsOut7Onchain($sum_txs_out_7_onchain)
    {

        if (is_null($sum_txs_out_7_onchain)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_7_onchain cannot be null');
        }

        $this->container['sum_txs_out_7_onchain'] = $sum_txs_out_7_onchain;

        return $this;
    }

    /**
     * Gets sum_txs_out_7_nft
     *
     * @return float|null
     */
    public function getSumTxsOut7Nft()
    {
        return $this->container['sum_txs_out_7_nft'];
    }

    /**
     * Sets sum_txs_out_7_nft
     *
     * @param float|null $sum_txs_out_7_nft Sum of all OUT NFT transactions during last week
     *
     * @return self
     */
    public function setSumTxsOut7Nft($sum_txs_out_7_nft)
    {

        if (is_null($sum_txs_out_7_nft)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_7_nft cannot be null');
        }

        $this->container['sum_txs_out_7_nft'] = $sum_txs_out_7_nft;

        return $this;
    }

    /**
     * Gets sum_txs_out_7_gaming
     *
     * @return float|null
     */
    public function getSumTxsOut7Gaming()
    {
        return $this->container['sum_txs_out_7_gaming'];
    }

    /**
     * Sets sum_txs_out_7_gaming
     *
     * @param float|null $sum_txs_out_7_gaming Sum of all OUT gaming transactions during last week
     *
     * @return self
     */
    public function setSumTxsOut7Gaming($sum_txs_out_7_gaming)
    {

        if (is_null($sum_txs_out_7_gaming)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_7_gaming cannot be null');
        }

        $this->container['sum_txs_out_7_gaming'] = $sum_txs_out_7_gaming;

        return $this;
    }

    /**
     * Gets sum_txs_out_7_gambling
     *
     * @return float|null
     */
    public function getSumTxsOut7Gambling()
    {
        return $this->container['sum_txs_out_7_gambling'];
    }

    /**
     * Sets sum_txs_out_7_gambling
     *
     * @param float|null $sum_txs_out_7_gambling Sum of all OUT gambling transactions during last week
     *
     * @return self
     */
    public function setSumTxsOut7Gambling($sum_txs_out_7_gambling)
    {

        if (is_null($sum_txs_out_7_gambling)) {
            throw new \InvalidArgumentException('non-nullable sum_txs_out_7_gambling cannot be null');
        }

        $this->container['sum_txs_out_7_gambling'] = $sum_txs_out_7_gambling;

        return $this;
    }

    /**
     * Gets max_balance_forever_onchain
     *
     * @return float|null
     */
    public function getMaxBalanceForeverOnchain()
    {
        return $this->container['max_balance_forever_onchain'];
    }

    /**
     * Sets max_balance_forever_onchain
     *
     * @param float|null $max_balance_forever_onchain Maximum balance
     *
     * @return self
     */
    public function setMaxBalanceForeverOnchain($max_balance_forever_onchain)
    {

        if (is_null($max_balance_forever_onchain)) {
            throw new \InvalidArgumentException('non-nullable max_balance_forever_onchain cannot be null');
        }

        $this->container['max_balance_forever_onchain'] = $max_balance_forever_onchain;

        return $this;
    }

    /**
     * Gets max_balance_forever_nft
     *
     * @return float|null
     */
    public function getMaxBalanceForeverNft()
    {
        return $this->container['max_balance_forever_nft'];
    }

    /**
     * Sets max_balance_forever_nft
     *
     * @param float|null $max_balance_forever_nft Maximum NFT balance
     *
     * @return self
     */
    public function setMaxBalanceForeverNft($max_balance_forever_nft)
    {

        if (is_null($max_balance_forever_nft)) {
            throw new \InvalidArgumentException('non-nullable max_balance_forever_nft cannot be null');
        }

        $this->container['max_balance_forever_nft'] = $max_balance_forever_nft;

        return $this;
    }

    /**
     * Gets max_balance_forever_gaming
     *
     * @return float|null
     */
    public function getMaxBalanceForeverGaming()
    {
        return $this->container['max_balance_forever_gaming'];
    }

    /**
     * Sets max_balance_forever_gaming
     *
     * @param float|null $max_balance_forever_gaming Maximum gaming balance
     *
     * @return self
     */
    public function setMaxBalanceForeverGaming($max_balance_forever_gaming)
    {

        if (is_null($max_balance_forever_gaming)) {
            throw new \InvalidArgumentException('non-nullable max_balance_forever_gaming cannot be null');
        }

        $this->container['max_balance_forever_gaming'] = $max_balance_forever_gaming;

        return $this;
    }

    /**
     * Gets max_balance_forever_gambling
     *
     * @return float|null
     */
    public function getMaxBalanceForeverGambling()
    {
        return $this->container['max_balance_forever_gambling'];
    }

    /**
     * Sets max_balance_forever_gambling
     *
     * @param float|null $max_balance_forever_gambling Maximum gambing balance
     *
     * @return self
     */
    public function setMaxBalanceForeverGambling($max_balance_forever_gambling)
    {

        if (is_null($max_balance_forever_gambling)) {
            throw new \InvalidArgumentException('non-nullable max_balance_forever_gambling cannot be null');
        }

        $this->container['max_balance_forever_gambling'] = $max_balance_forever_gambling;

        return $this;
    }

    /**
     * Gets max_balance_365_onchain
     *
     * @return float|null
     */
    public function getMaxBalance365Onchain()
    {
        return $this->container['max_balance_365_onchain'];
    }

    /**
     * Sets max_balance_365_onchain
     *
     * @param float|null $max_balance_365_onchain Maximum balance during last year
     *
     * @return self
     */
    public function setMaxBalance365Onchain($max_balance_365_onchain)
    {

        if (is_null($max_balance_365_onchain)) {
            throw new \InvalidArgumentException('non-nullable max_balance_365_onchain cannot be null');
        }

        $this->container['max_balance_365_onchain'] = $max_balance_365_onchain;

        return $this;
    }

    /**
     * Gets max_balance_365_nft
     *
     * @return float|null
     */
    public function getMaxBalance365Nft()
    {
        return $this->container['max_balance_365_nft'];
    }

    /**
     * Sets max_balance_365_nft
     *
     * @param float|null $max_balance_365_nft Maximum NFT balance during last year
     *
     * @return self
     */
    public function setMaxBalance365Nft($max_balance_365_nft)
    {

        if (is_null($max_balance_365_nft)) {
            throw new \InvalidArgumentException('non-nullable max_balance_365_nft cannot be null');
        }

        $this->container['max_balance_365_nft'] = $max_balance_365_nft;

        return $this;
    }

    /**
     * Gets max_balance_365_gaming
     *
     * @return float|null
     */
    public function getMaxBalance365Gaming()
    {
        return $this->container['max_balance_365_gaming'];
    }

    /**
     * Sets max_balance_365_gaming
     *
     * @param float|null $max_balance_365_gaming Maximum gaming balance during last year
     *
     * @return self
     */
    public function setMaxBalance365Gaming($max_balance_365_gaming)
    {

        if (is_null($max_balance_365_gaming)) {
            throw new \InvalidArgumentException('non-nullable max_balance_365_gaming cannot be null');
        }

        $this->container['max_balance_365_gaming'] = $max_balance_365_gaming;

        return $this;
    }

    /**
     * Gets max_balance_365_gambling
     *
     * @return float|null
     */
    public function getMaxBalance365Gambling()
    {
        return $this->container['max_balance_365_gambling'];
    }

    /**
     * Sets max_balance_365_gambling
     *
     * @param float|null $max_balance_365_gambling Maximum gambling balance during last year
     *
     * @return self
     */
    public function setMaxBalance365Gambling($max_balance_365_gambling)
    {

        if (is_null($max_balance_365_gambling)) {
            throw new \InvalidArgumentException('non-nullable max_balance_365_gambling cannot be null');
        }

        $this->container['max_balance_365_gambling'] = $max_balance_365_gambling;

        return $this;
    }

    /**
     * Gets max_balance_31_60_onchain
     *
     * @return float|null
     */
    public function getMaxBalance3160Onchain()
    {
        return $this->container['max_balance_31_60_onchain'];
    }

    /**
     * Sets max_balance_31_60_onchain
     *
     * @param float|null $max_balance_31_60_onchain Maximum balance during previous month
     *
     * @return self
     */
    public function setMaxBalance3160Onchain($max_balance_31_60_onchain)
    {

        if (is_null($max_balance_31_60_onchain)) {
            throw new \InvalidArgumentException('non-nullable max_balance_31_60_onchain cannot be null');
        }

        $this->container['max_balance_31_60_onchain'] = $max_balance_31_60_onchain;

        return $this;
    }

    /**
     * Gets max_balance_31_60_nft
     *
     * @return float|null
     */
    public function getMaxBalance3160Nft()
    {
        return $this->container['max_balance_31_60_nft'];
    }

    /**
     * Sets max_balance_31_60_nft
     *
     * @param float|null $max_balance_31_60_nft Maximum NFT balance during previous month
     *
     * @return self
     */
    public function setMaxBalance3160Nft($max_balance_31_60_nft)
    {

        if (is_null($max_balance_31_60_nft)) {
            throw new \InvalidArgumentException('non-nullable max_balance_31_60_nft cannot be null');
        }

        $this->container['max_balance_31_60_nft'] = $max_balance_31_60_nft;

        return $this;
    }

    /**
     * Gets max_balance_31_60_gaming
     *
     * @return float|null
     */
    public function getMaxBalance3160Gaming()
    {
        return $this->container['max_balance_31_60_gaming'];
    }

    /**
     * Sets max_balance_31_60_gaming
     *
     * @param float|null $max_balance_31_60_gaming Maximum gaming balance during previous month
     *
     * @return self
     */
    public function setMaxBalance3160Gaming($max_balance_31_60_gaming)
    {

        if (is_null($max_balance_31_60_gaming)) {
            throw new \InvalidArgumentException('non-nullable max_balance_31_60_gaming cannot be null');
        }

        $this->container['max_balance_31_60_gaming'] = $max_balance_31_60_gaming;

        return $this;
    }

    /**
     * Gets max_balance_31_60_gambling
     *
     * @return float|null
     */
    public function getMaxBalance3160Gambling()
    {
        return $this->container['max_balance_31_60_gambling'];
    }

    /**
     * Sets max_balance_31_60_gambling
     *
     * @param float|null $max_balance_31_60_gambling Maximum gambling balance during previous month
     *
     * @return self
     */
    public function setMaxBalance3160Gambling($max_balance_31_60_gambling)
    {

        if (is_null($max_balance_31_60_gambling)) {
            throw new \InvalidArgumentException('non-nullable max_balance_31_60_gambling cannot be null');
        }

        $this->container['max_balance_31_60_gambling'] = $max_balance_31_60_gambling;

        return $this;
    }

    /**
     * Gets max_balance_30_onchain
     *
     * @return float|null
     */
    public function getMaxBalance30Onchain()
    {
        return $this->container['max_balance_30_onchain'];
    }

    /**
     * Sets max_balance_30_onchain
     *
     * @param float|null $max_balance_30_onchain Maximum balance during last month
     *
     * @return self
     */
    public function setMaxBalance30Onchain($max_balance_30_onchain)
    {

        if (is_null($max_balance_30_onchain)) {
            throw new \InvalidArgumentException('non-nullable max_balance_30_onchain cannot be null');
        }

        $this->container['max_balance_30_onchain'] = $max_balance_30_onchain;

        return $this;
    }

    /**
     * Gets max_balance_30_nft
     *
     * @return float|null
     */
    public function getMaxBalance30Nft()
    {
        return $this->container['max_balance_30_nft'];
    }

    /**
     * Sets max_balance_30_nft
     *
     * @param float|null $max_balance_30_nft Maximum NFT balance during last month
     *
     * @return self
     */
    public function setMaxBalance30Nft($max_balance_30_nft)
    {

        if (is_null($max_balance_30_nft)) {
            throw new \InvalidArgumentException('non-nullable max_balance_30_nft cannot be null');
        }

        $this->container['max_balance_30_nft'] = $max_balance_30_nft;

        return $this;
    }

    /**
     * Gets max_balance_30_gaming
     *
     * @return float|null
     */
    public function getMaxBalance30Gaming()
    {
        return $this->container['max_balance_30_gaming'];
    }

    /**
     * Sets max_balance_30_gaming
     *
     * @param float|null $max_balance_30_gaming Maximum gaming balance during last month
     *
     * @return self
     */
    public function setMaxBalance30Gaming($max_balance_30_gaming)
    {

        if (is_null($max_balance_30_gaming)) {
            throw new \InvalidArgumentException('non-nullable max_balance_30_gaming cannot be null');
        }

        $this->container['max_balance_30_gaming'] = $max_balance_30_gaming;

        return $this;
    }

    /**
     * Gets max_balance_30_gambling
     *
     * @return float|null
     */
    public function getMaxBalance30Gambling()
    {
        return $this->container['max_balance_30_gambling'];
    }

    /**
     * Sets max_balance_30_gambling
     *
     * @param float|null $max_balance_30_gambling Maximum gambling balance during last month
     *
     * @return self
     */
    public function setMaxBalance30Gambling($max_balance_30_gambling)
    {

        if (is_null($max_balance_30_gambling)) {
            throw new \InvalidArgumentException('non-nullable max_balance_30_gambling cannot be null');
        }

        $this->container['max_balance_30_gambling'] = $max_balance_30_gambling;

        return $this;
    }

    /**
     * Gets max_balance_7_onchain
     *
     * @return float|null
     */
    public function getMaxBalance7Onchain()
    {
        return $this->container['max_balance_7_onchain'];
    }

    /**
     * Sets max_balance_7_onchain
     *
     * @param float|null $max_balance_7_onchain Maximum balance during last week
     *
     * @return self
     */
    public function setMaxBalance7Onchain($max_balance_7_onchain)
    {

        if (is_null($max_balance_7_onchain)) {
            throw new \InvalidArgumentException('non-nullable max_balance_7_onchain cannot be null');
        }

        $this->container['max_balance_7_onchain'] = $max_balance_7_onchain;

        return $this;
    }

    /**
     * Gets max_balance_7_nft
     *
     * @return float|null
     */
    public function getMaxBalance7Nft()
    {
        return $this->container['max_balance_7_nft'];
    }

    /**
     * Sets max_balance_7_nft
     *
     * @param float|null $max_balance_7_nft Maximum NFT balance during last week
     *
     * @return self
     */
    public function setMaxBalance7Nft($max_balance_7_nft)
    {

        if (is_null($max_balance_7_nft)) {
            throw new \InvalidArgumentException('non-nullable max_balance_7_nft cannot be null');
        }

        $this->container['max_balance_7_nft'] = $max_balance_7_nft;

        return $this;
    }

    /**
     * Gets max_balance_7_gaming
     *
     * @return float|null
     */
    public function getMaxBalance7Gaming()
    {
        return $this->container['max_balance_7_gaming'];
    }

    /**
     * Sets max_balance_7_gaming
     *
     * @param float|null $max_balance_7_gaming Maximum gaming balance during last week
     *
     * @return self
     */
    public function setMaxBalance7Gaming($max_balance_7_gaming)
    {

        if (is_null($max_balance_7_gaming)) {
            throw new \InvalidArgumentException('non-nullable max_balance_7_gaming cannot be null');
        }

        $this->container['max_balance_7_gaming'] = $max_balance_7_gaming;

        return $this;
    }

    /**
     * Gets max_balance_7_gambling
     *
     * @return float|null
     */
    public function getMaxBalance7Gambling()
    {
        return $this->container['max_balance_7_gambling'];
    }

    /**
     * Sets max_balance_7_gambling
     *
     * @param float|null $max_balance_7_gambling Maximum gambling balance during last week
     *
     * @return self
     */
    public function setMaxBalance7Gambling($max_balance_7_gambling)
    {

        if (is_null($max_balance_7_gambling)) {
            throw new \InvalidArgumentException('non-nullable max_balance_7_gambling cannot be null');
        }

        $this->container['max_balance_7_gambling'] = $max_balance_7_gambling;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


